# Generated by Django 3.2.7 on 2021-09-21 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0002_address_donor_recyclingcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclingcenter',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users_auth.address'),
        ),
        migrations.AlterField(
            model_name='recyclingcenter',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
