# Generated by Django 3.2.7 on 2021-09-21 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0003_auto_20210921_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclingcenter',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_auth.address'),
        ),
    ]
