# Generated by Django 3.2.7 on 2021-11-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0004_alter_recyclingcenter_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pass_key', models.CharField(max_length=200)),
                ('used', models.BooleanField(default=False)),
                ('expiration_date', models.DateTimeField()),
                ('situation', models.CharField(choices=[('A', 'DISPONÍVEL'), ('E', 'EXPIRADO')], max_length=1)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_auth.donor')),
            ],
        ),
    ]
