# Generated by Django 3.2.7 on 2021-11-24 13:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0006_alter_coupon_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingcenter',
            name='materials',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
    ]
