# Generated by Django 3.2.7 on 2021-10-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_donation', '0002_auto_20210920_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status_donation',
            field=models.CharField(choices=[('0', 'Confirmada'), ('1', 'Precisa Revisar'), ('2', 'Cancelada'), ('3', 'Aguardando Materiais')], max_length=1),
        ),
    ]
